//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    public partial class Persona : object
    {
        
        private string CelulaIdentidadField;
        
        private string NombresField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        private System.DateTime FechaNacimientoField;
        
        private string SexoField;
        
        private string EstadoCivilField;
        
        private string NombrePadreField;
        
        private string ApellidosPadreField;
        
        private string NombreMadreField;
        
        private string ApellidosMadreField;
        
        private string CedulaIdentidadEsposoField;
        
        private string NombresEsposoField;
        
        private string PrimerApellidoEsposoField;
        
        private string SegundoApellidoEsposoField;
        
        private string CedulaIdentidadEsposaField;
        
        private string NombresEsposaField;
        
        private string PrimerApellidoEsposaField;
        
        private string SegundoApellidoEsposaField;
        
        private System.DateTime FechaDefuncionField;
        
        private string CausaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CelulaIdentidad
        {
            get
            {
                return this.CelulaIdentidadField;
            }
            set
            {
                this.CelulaIdentidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string EstadoCivil
        {
            get
            {
                return this.EstadoCivilField;
            }
            set
            {
                this.EstadoCivilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NombrePadre
        {
            get
            {
                return this.NombrePadreField;
            }
            set
            {
                this.NombrePadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ApellidosPadre
        {
            get
            {
                return this.ApellidosPadreField;
            }
            set
            {
                this.ApellidosPadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string NombreMadre
        {
            get
            {
                return this.NombreMadreField;
            }
            set
            {
                this.NombreMadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ApellidosMadre
        {
            get
            {
                return this.ApellidosMadreField;
            }
            set
            {
                this.ApellidosMadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string CedulaIdentidadEsposo
        {
            get
            {
                return this.CedulaIdentidadEsposoField;
            }
            set
            {
                this.CedulaIdentidadEsposoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string NombresEsposo
        {
            get
            {
                return this.NombresEsposoField;
            }
            set
            {
                this.NombresEsposoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string PrimerApellidoEsposo
        {
            get
            {
                return this.PrimerApellidoEsposoField;
            }
            set
            {
                this.PrimerApellidoEsposoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string SegundoApellidoEsposo
        {
            get
            {
                return this.SegundoApellidoEsposoField;
            }
            set
            {
                this.SegundoApellidoEsposoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string CedulaIdentidadEsposa
        {
            get
            {
                return this.CedulaIdentidadEsposaField;
            }
            set
            {
                this.CedulaIdentidadEsposaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string NombresEsposa
        {
            get
            {
                return this.NombresEsposaField;
            }
            set
            {
                this.NombresEsposaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string PrimerApellidoEsposa
        {
            get
            {
                return this.PrimerApellidoEsposaField;
            }
            set
            {
                this.PrimerApellidoEsposaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string SegundoApellidoEsposa
        {
            get
            {
                return this.SegundoApellidoEsposaField;
            }
            set
            {
                this.SegundoApellidoEsposaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.DateTime FechaDefuncion
        {
            get
            {
                return this.FechaDefuncionField;
            }
            set
            {
                this.FechaDefuncionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Causa
        {
            get
            {
                return this.CausaField;
            }
            set
            {
                this.CausaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Datos.WebServiceSoap")]
    public interface WebServiceSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CelulaIdentidad del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        Datos.ObtenerDatosResponse ObtenerDatos(Datos.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<Datos.ObtenerDatosResponse> ObtenerDatosAsync(Datos.ObtenerDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CelulaIdentidad del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoNacimiento", ReplyAction="*")]
        Datos.ObtenerCertificadoNacimientoResponse ObtenerCertificadoNacimiento(Datos.ObtenerCertificadoNacimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoNacimiento", ReplyAction="*")]
        System.Threading.Tasks.Task<Datos.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(Datos.ObtenerCertificadoNacimientoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CelulaIdentidad del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoMatrimonio", ReplyAction="*")]
        Datos.ObtenerCertificadoMatrimonioResponse ObtenerCertificadoMatrimonio(Datos.ObtenerCertificadoMatrimonioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoMatrimonio", ReplyAction="*")]
        System.Threading.Tasks.Task<Datos.ObtenerCertificadoMatrimonioResponse> ObtenerCertificadoMatrimonioAsync(Datos.ObtenerCertificadoMatrimonioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CelulaIdentidad del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDefuncion", ReplyAction="*")]
        Datos.ObtenerCertificadoDefuncionResponse ObtenerCertificadoDefuncion(Datos.ObtenerCertificadoDefuncionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDefuncion", ReplyAction="*")]
        System.Threading.Tasks.Task<Datos.ObtenerCertificadoDefuncionResponse> ObtenerCertificadoDefuncionAsync(Datos.ObtenerCertificadoDefuncionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest()
        {
        }
        
        public ObtenerDatosRequest(Datos.ObtenerDatosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CelulaIdentidad;
        
        public ObtenerDatosRequestBody()
        {
        }
        
        public ObtenerDatosRequestBody(string CelulaIdentidad)
        {
            this.CelulaIdentidad = CelulaIdentidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ObtenerDatosResponseBody Body;
        
        public ObtenerDatosResponse()
        {
        }
        
        public ObtenerDatosResponse(Datos.ObtenerDatosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Datos.Persona ObtenerDatosResult;
        
        public ObtenerDatosResponseBody()
        {
        }
        
        public ObtenerDatosResponseBody(Datos.Persona ObtenerDatosResult)
        {
            this.ObtenerDatosResult = ObtenerDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimiento", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ObtenerCertificadoNacimientoRequestBody Body;
        
        public ObtenerCertificadoNacimientoRequest()
        {
        }
        
        public ObtenerCertificadoNacimientoRequest(Datos.ObtenerCertificadoNacimientoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoNacimientoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CelulaIdentidad;
        
        public ObtenerCertificadoNacimientoRequestBody()
        {
        }
        
        public ObtenerCertificadoNacimientoRequestBody(string CelulaIdentidad)
        {
            this.CelulaIdentidad = CelulaIdentidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ObtenerCertificadoNacimientoResponseBody Body;
        
        public ObtenerCertificadoNacimientoResponse()
        {
        }
        
        public ObtenerCertificadoNacimientoResponse(Datos.ObtenerCertificadoNacimientoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoNacimientoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Datos.Persona ObtenerCertificadoNacimientoResult;
        
        public ObtenerCertificadoNacimientoResponseBody()
        {
        }
        
        public ObtenerCertificadoNacimientoResponseBody(Datos.Persona ObtenerCertificadoNacimientoResult)
        {
            this.ObtenerCertificadoNacimientoResult = ObtenerCertificadoNacimientoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoMatrimonioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoMatrimonio", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ObtenerCertificadoMatrimonioRequestBody Body;
        
        public ObtenerCertificadoMatrimonioRequest()
        {
        }
        
        public ObtenerCertificadoMatrimonioRequest(Datos.ObtenerCertificadoMatrimonioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoMatrimonioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CelulaIdentidad;
        
        public ObtenerCertificadoMatrimonioRequestBody()
        {
        }
        
        public ObtenerCertificadoMatrimonioRequestBody(string CelulaIdentidad)
        {
            this.CelulaIdentidad = CelulaIdentidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoMatrimonioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoMatrimonioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ObtenerCertificadoMatrimonioResponseBody Body;
        
        public ObtenerCertificadoMatrimonioResponse()
        {
        }
        
        public ObtenerCertificadoMatrimonioResponse(Datos.ObtenerCertificadoMatrimonioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoMatrimonioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Datos.Persona ObtenerCertificadoMatrimonioResult;
        
        public ObtenerCertificadoMatrimonioResponseBody()
        {
        }
        
        public ObtenerCertificadoMatrimonioResponseBody(Datos.Persona ObtenerCertificadoMatrimonioResult)
        {
            this.ObtenerCertificadoMatrimonioResult = ObtenerCertificadoMatrimonioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDefuncionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDefuncion", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ObtenerCertificadoDefuncionRequestBody Body;
        
        public ObtenerCertificadoDefuncionRequest()
        {
        }
        
        public ObtenerCertificadoDefuncionRequest(Datos.ObtenerCertificadoDefuncionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDefuncionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CelulaIdentidad;
        
        public ObtenerCertificadoDefuncionRequestBody()
        {
        }
        
        public ObtenerCertificadoDefuncionRequestBody(string CelulaIdentidad)
        {
            this.CelulaIdentidad = CelulaIdentidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDefuncionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDefuncionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ObtenerCertificadoDefuncionResponseBody Body;
        
        public ObtenerCertificadoDefuncionResponse()
        {
        }
        
        public ObtenerCertificadoDefuncionResponse(Datos.ObtenerCertificadoDefuncionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDefuncionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Datos.Persona ObtenerCertificadoDefuncionResult;
        
        public ObtenerCertificadoDefuncionResponseBody()
        {
        }
        
        public ObtenerCertificadoDefuncionResponseBody(Datos.Persona ObtenerCertificadoDefuncionResult)
        {
            this.ObtenerCertificadoDefuncionResult = ObtenerCertificadoDefuncionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WebServiceSoapChannel : Datos.WebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Datos.WebServiceSoap>, Datos.WebServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Datos.ObtenerDatosResponse Datos.WebServiceSoap.ObtenerDatos(Datos.ObtenerDatosRequest request)
        {
            return base.Channel.ObtenerDatos(request);
        }
        
        public Datos.Persona ObtenerDatos(string CelulaIdentidad)
        {
            Datos.ObtenerDatosRequest inValue = new Datos.ObtenerDatosRequest();
            inValue.Body = new Datos.ObtenerDatosRequestBody();
            inValue.Body.CelulaIdentidad = CelulaIdentidad;
            Datos.ObtenerDatosResponse retVal = ((Datos.WebServiceSoap)(this)).ObtenerDatos(inValue);
            return retVal.Body.ObtenerDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Datos.ObtenerDatosResponse> Datos.WebServiceSoap.ObtenerDatosAsync(Datos.ObtenerDatosRequest request)
        {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Datos.ObtenerDatosResponse> ObtenerDatosAsync(string CelulaIdentidad)
        {
            Datos.ObtenerDatosRequest inValue = new Datos.ObtenerDatosRequest();
            inValue.Body = new Datos.ObtenerDatosRequestBody();
            inValue.Body.CelulaIdentidad = CelulaIdentidad;
            return ((Datos.WebServiceSoap)(this)).ObtenerDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Datos.ObtenerCertificadoNacimientoResponse Datos.WebServiceSoap.ObtenerCertificadoNacimiento(Datos.ObtenerCertificadoNacimientoRequest request)
        {
            return base.Channel.ObtenerCertificadoNacimiento(request);
        }
        
        public Datos.Persona ObtenerCertificadoNacimiento(string CelulaIdentidad)
        {
            Datos.ObtenerCertificadoNacimientoRequest inValue = new Datos.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new Datos.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body.CelulaIdentidad = CelulaIdentidad;
            Datos.ObtenerCertificadoNacimientoResponse retVal = ((Datos.WebServiceSoap)(this)).ObtenerCertificadoNacimiento(inValue);
            return retVal.Body.ObtenerCertificadoNacimientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Datos.ObtenerCertificadoNacimientoResponse> Datos.WebServiceSoap.ObtenerCertificadoNacimientoAsync(Datos.ObtenerCertificadoNacimientoRequest request)
        {
            return base.Channel.ObtenerCertificadoNacimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Datos.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(string CelulaIdentidad)
        {
            Datos.ObtenerCertificadoNacimientoRequest inValue = new Datos.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new Datos.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body.CelulaIdentidad = CelulaIdentidad;
            return ((Datos.WebServiceSoap)(this)).ObtenerCertificadoNacimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Datos.ObtenerCertificadoMatrimonioResponse Datos.WebServiceSoap.ObtenerCertificadoMatrimonio(Datos.ObtenerCertificadoMatrimonioRequest request)
        {
            return base.Channel.ObtenerCertificadoMatrimonio(request);
        }
        
        public Datos.Persona ObtenerCertificadoMatrimonio(string CelulaIdentidad)
        {
            Datos.ObtenerCertificadoMatrimonioRequest inValue = new Datos.ObtenerCertificadoMatrimonioRequest();
            inValue.Body = new Datos.ObtenerCertificadoMatrimonioRequestBody();
            inValue.Body.CelulaIdentidad = CelulaIdentidad;
            Datos.ObtenerCertificadoMatrimonioResponse retVal = ((Datos.WebServiceSoap)(this)).ObtenerCertificadoMatrimonio(inValue);
            return retVal.Body.ObtenerCertificadoMatrimonioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Datos.ObtenerCertificadoMatrimonioResponse> Datos.WebServiceSoap.ObtenerCertificadoMatrimonioAsync(Datos.ObtenerCertificadoMatrimonioRequest request)
        {
            return base.Channel.ObtenerCertificadoMatrimonioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Datos.ObtenerCertificadoMatrimonioResponse> ObtenerCertificadoMatrimonioAsync(string CelulaIdentidad)
        {
            Datos.ObtenerCertificadoMatrimonioRequest inValue = new Datos.ObtenerCertificadoMatrimonioRequest();
            inValue.Body = new Datos.ObtenerCertificadoMatrimonioRequestBody();
            inValue.Body.CelulaIdentidad = CelulaIdentidad;
            return ((Datos.WebServiceSoap)(this)).ObtenerCertificadoMatrimonioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Datos.ObtenerCertificadoDefuncionResponse Datos.WebServiceSoap.ObtenerCertificadoDefuncion(Datos.ObtenerCertificadoDefuncionRequest request)
        {
            return base.Channel.ObtenerCertificadoDefuncion(request);
        }
        
        public Datos.Persona ObtenerCertificadoDefuncion(string CelulaIdentidad)
        {
            Datos.ObtenerCertificadoDefuncionRequest inValue = new Datos.ObtenerCertificadoDefuncionRequest();
            inValue.Body = new Datos.ObtenerCertificadoDefuncionRequestBody();
            inValue.Body.CelulaIdentidad = CelulaIdentidad;
            Datos.ObtenerCertificadoDefuncionResponse retVal = ((Datos.WebServiceSoap)(this)).ObtenerCertificadoDefuncion(inValue);
            return retVal.Body.ObtenerCertificadoDefuncionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Datos.ObtenerCertificadoDefuncionResponse> Datos.WebServiceSoap.ObtenerCertificadoDefuncionAsync(Datos.ObtenerCertificadoDefuncionRequest request)
        {
            return base.Channel.ObtenerCertificadoDefuncionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Datos.ObtenerCertificadoDefuncionResponse> ObtenerCertificadoDefuncionAsync(string CelulaIdentidad)
        {
            Datos.ObtenerCertificadoDefuncionRequest inValue = new Datos.ObtenerCertificadoDefuncionRequest();
            inValue.Body = new Datos.ObtenerCertificadoDefuncionRequestBody();
            inValue.Body.CelulaIdentidad = CelulaIdentidad;
            return ((Datos.WebServiceSoap)(this)).ObtenerCertificadoDefuncionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56278/WebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56278/WebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceSoap,
            
            WebServiceSoap12,
        }
    }
}
